version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dev-jb
      POSTGRES_PASSWORD: dev-jb
      POSTGRES_DB: dev-jb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

