version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: user1
      POSTGRES_DB: dev
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
