// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: company.sql

package db

import (
	"context"
	"database/sql"
)

const createCompany = `-- name: CreateCompany :one

INSERT INTO Company (
  user_id,
  name,
  email,
  phone,
  website,
  logo,
  description,
  created_at,
  updated_at
) VALUES (
  $1, -- user_id
  $2, -- name
  $3, -- email
  $4, -- phone
  $5, -- website
  $6, -- logo
  $7, -- description
  CURRENT_TIMESTAMP, -- created_at
  CURRENT_TIMESTAMP -- updated_at
) RETURNING id
`

type CreateCompanyParams struct {
	UserID      sql.NullInt32  `json:"user_id"`
	Name        sql.NullString `json:"name"`
	Email       sql.NullString `json:"email"`
	Phone       sql.NullString `json:"phone"`
	Website     sql.NullString `json:"website"`
	Logo        sql.NullString `json:"logo"`
	Description sql.NullString `json:"description"`
}

// company.sql
func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (int32, error) {
	row := q.queryRow(ctx, q.createCompanyStmt, createCompany,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Website,
		arg.Logo,
		arg.Description,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteCompany = `-- name: DeleteCompany :exec

DELETE FROM Company
WHERE id = $1
`

// Specify the condition for updating, such as the "id" column
func (q *Queries) DeleteCompany(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.deleteCompanyStmt, deleteCompany, id)
	return err
}

const getCompanies = `-- name: GetCompanies :many
SELECT id, user_id, name, email, phone, website, logo, description, created_at, updated_at FROM Company
`

func (q *Queries) GetCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.query(ctx, q.getCompaniesStmt, getCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Website,
			&i.Logo,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :exec
UPDATE Company
SET name = $1, email = $2, phone = $3, website = $4, logo = $5, description = $6, updated_at = CURRENT_TIMESTAMP
WHERE id = $7
`

type UpdateCompanyParams struct {
	Name        sql.NullString `json:"name"`
	Email       sql.NullString `json:"email"`
	Phone       sql.NullString `json:"phone"`
	Website     sql.NullString `json:"website"`
	Logo        sql.NullString `json:"logo"`
	Description sql.NullString `json:"description"`
	ID          int32          `json:"id"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) error {
	_, err := q.exec(ctx, q.updateCompanyStmt, updateCompany,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Website,
		arg.Logo,
		arg.Description,
		arg.ID,
	)
	return err
}
