// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: jobseekerskill.sql

package db

import (
	"context"
)

const deleteJobSeekerSkill = `-- name: DeleteJobSeekerSkill :exec
DELETE FROM JobSeekerSkill WHERE job_seeker_id = $1 AND skill_id = $2
`

type DeleteJobSeekerSkillParams struct {
	JobSeekerID int32 `json:"job_seeker_id"`
	SkillID     int32 `json:"skill_id"`
}

func (q *Queries) DeleteJobSeekerSkill(ctx context.Context, arg DeleteJobSeekerSkillParams) error {
	_, err := q.exec(ctx, q.deleteJobSeekerSkillStmt, deleteJobSeekerSkill, arg.JobSeekerID, arg.SkillID)
	return err
}

const insertJobSeekerSkill = `-- name: InsertJobSeekerSkill :exec
INSERT INTO JobSeekerSkill (job_seeker_id, skill_id)
VALUES ($1, $2)
`

type InsertJobSeekerSkillParams struct {
	JobSeekerID int32 `json:"job_seeker_id"`
	SkillID     int32 `json:"skill_id"`
}

func (q *Queries) InsertJobSeekerSkill(ctx context.Context, arg InsertJobSeekerSkillParams) error {
	_, err := q.exec(ctx, q.insertJobSeekerSkillStmt, insertJobSeekerSkill, arg.JobSeekerID, arg.SkillID)
	return err
}

const selectJobSeekerSkillsByJobSeekerID = `-- name: SelectJobSeekerSkillsByJobSeekerID :many
SELECT job_seeker_id, skill_id FROM JobSeekerSkill WHERE job_seeker_id = $1
`

func (q *Queries) SelectJobSeekerSkillsByJobSeekerID(ctx context.Context, jobSeekerID int32) ([]Jobseekerskill, error) {
	rows, err := q.query(ctx, q.selectJobSeekerSkillsByJobSeekerIDStmt, selectJobSeekerSkillsByJobSeekerID, jobSeekerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Jobseekerskill
	for rows.Next() {
		var i Jobseekerskill
		if err := rows.Scan(&i.JobSeekerID, &i.SkillID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
